const TEMPLATES = [
	{ turrets: ["BaBaMG"                      ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs"  , name: "*BaBa MG* *BaBa Body* BaBaLegs"                               },
	{ turrets: ["BaBaMG"                      ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs"  , name: "*BaBa MG* *BaBa Body* BaBaLegs"                               },
	{ turrets: ["bTrikeMG"                    ], body: "B4body-sml-trike01", propulsion: "BaBaProp"  , name: "*Trike MG* *Trike Body* BaBaProp"                             },
	{ turrets: ["BuggyMG"                     ], body: "B3body-sml-buggy01", propulsion: "BaBaProp"  , name: "*Buggy MG* *Buggy Body* BaBaProp"                             },
	{ turrets: ["BJeepMG"                     ], body: "B2JeepBody"        , propulsion: "BaBaProp"  , name: "*Jeep MG* *Jeep Body* BaBaProp"                               },
	{ turrets: ["BusCannon"                   ], body: "BusBody"           , propulsion: "BaBaProp"  , name: "*BusCannon* *School Bus Body* BaBaProp"                       },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body1REC"          , propulsion: "wheeled01" , name: "Light Cannon Viper Wheels"                                    },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body1REC"          , propulsion: "HalfTrack" , name: "Light Cannon Viper Half-tracks"                               },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body8MBT"          , propulsion: "HalfTrack" , name: "Light Cannon Scorpion Half-tracks"                            },
	{ turrets: ["CyborgCannon"                ], body: "CyborgLightBody"   , propulsion: "CyborgLegs", name: "Heavy Gunner Cyborg Light Body Cyborg Propulsion"             },
	{ turrets: ["Cannon2A-TMk1"               ], body: "Body5REC"          , propulsion: "wheeled01" , name: "Medium Cannon Cobra Wheels"                                   },
	{ turrets: ["Cannon2A-TMk1"               ], body: "Body8MBT"          , propulsion: "HalfTrack" , name: "Medium Cannon Scorpion Half-tracks"                           },
	{ turrets: ["Cannon4AUTOMk1"              ], body: "Body4ABT"          , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Bug Half-tracks"                        },
	{ turrets: ["Cannon4AUTOMk1"              ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Cobra Half-tracks"                      },
	{ turrets: ["Rocket-BB"                   ], body: "Body2SUP"          , propulsion: "HalfTrack" , name: "Bunker Buster Leopard Half-tracks"                            },
	{ turrets: ["Cannon4AUTOMk1"              ], body: "Body8MBT"          , propulsion: "tracked01" , name: "Hyper Velocity Cannon Scorpion Tracks"                        },
	{ turrets: ["Cannon5VulcanMk1"            ], body: "Body5REC"          , propulsion: "tracked01" , name: "Assault Cannon Cobra Tracks"                                  },
	{ turrets: ["Cyb-Hvywpn-Acannon"          ], body: "CyborgHeavyBody"   , propulsion: "CyborgLegs", name: "Super Auto-Cannon Cyborg Cyborg Heavy Body Cyborg Propulsion" },
	{ turrets: ["Cannon5VulcanMk1"            ], body: "Body6SUPP"         , propulsion: "tracked01" , name: "Assault Cannon Panther Tracks"                                },
	{ turrets: ["Cannon375mmMk1"              ], body: "Body12SUP"         , propulsion: "tracked01" , name: "Heavy Cannon Mantis Tracks"                                   },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP"         , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Panther VTOL"                              },
	{ turrets: ["Cannon375mmMk1"              ], body: "Body12SUP"         , propulsion: "tracked01" , name: "Heavy Cannon Mantis Tracks"                                   },
	{ turrets: ["Cannon6TwinAslt"             ], body: "Body12SUP"         , propulsion: "tracked01" , name: "Twin Assault Cannon Mantis Tracks"                            },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP"         , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Panther VTOL"                              },
	{ turrets: ["Cannon6TwinAslt"             ], body: "Body12SUP"         , propulsion: "tracked01" , name: "Twin Assault Cannon Mantis Tracks"                            },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP"         , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Panther VTOL"                              },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP"         , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Panther VTOL"                              },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP"         , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Panther VTOL"                              },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC"          , propulsion: "tracked01" , name: "Needle Gun Tiger Tracks"                                      },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Retribution VTOL"                          },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Retribution VTOL"                          },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Bunker Buster Retribution VTOL"                          },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT"          , propulsion: "tracked01" , name: "Needle Gun Retribution Tracks"                                },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Rail Gun Retribution VTOL"                               },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Rail Gun Retribution VTOL"                               },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Rail Gun Retribution VTOL"                               },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT"         , propulsion: "tracked01" , name: "Rail Gun Vengeance Tracks"                                    },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Rail Gun Retribution VTOL"                               },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body7ABT"          , propulsion: "V-Tol"     , name: "VTOL Particle Gun Retribution VTOL"                           },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body10MBT"         , propulsion: "V-Tol"     , name: "VTOL Particle Gun Vengeance VTOL"                             },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body13SUP"         , propulsion: "V-Tol"     , name: "VTOL Particle Gun Wyvern VTOL"                                },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP"         , propulsion: "tracked01" , name: "Gauss Cannon Wyvern Tracks"                                   },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP"         , propulsion: "hover01"   , name: "Gauss Cannon Seraph Missile Array Dragon Hover"               },
	{ turrets: ["x3_Missile-HvySAM", "x3_RailGun3Mk1"], body:"x3_Body14SUP", propulsion: "x3_tracked01", name: "Super Big Gauss Cannon Super Big Vindicator Sam Super Big Dragon Super Big Tracks" },
];
