const TEMPLATES = [
	null,
	null,
	null,
	null,
	null,
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"           },
	{ turrets: ["bTrikeMG"        ], body: "B4body-sml-trike01", propulsion: "BaBaProp" , name: "*Trike MG* *Trike Body* BaBaProp"         },
	{ turrets: ["BuggyMG"         ], body: "B3body-sml-buggy01", propulsion: "BaBaProp" , name: "*Buggy MG* *Buggy Body* BaBaProp"         },
	{ turrets: ["BJeepMG"         ], body: "B2JeepBody"        , propulsion: "BaBaProp" , name: "*Jeep MG* *Jeep Body* BaBaProp"           },
	{ turrets: ["BusCannon"       ], body: "BusBody"           , propulsion: "BaBaProp" , name: "*BusCannon* *School Bus Body* BaBaProp"   },
	{ turrets: ["Cannon1Mk1"      ], body: "Body1REC"          , propulsion: "wheeled01", name: "Light Cannon Viper Wheels"                },
	{ turrets: ["Cannon1Mk1"      ], body: "Body1REC"          , propulsion: "HalfTrack", name: "Light Cannon Viper Half-tracks"           },
	{ turrets: ["Cannon1Mk1"      ], body: "Body8MBT"          , propulsion: "HalfTrack", name: "Light Cannon Scorpion Half-tracks"        },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body5REC"          , propulsion: "wheeled01", name: "Medium Cannon Cobra Wheels"               },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body5REC"          , propulsion: "HalfTrack", name: "Medium Cannon Cobra Half-tracks"          },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body5REC"          , propulsion: "HalfTrack", name: "Hyper Velocity Cannon Cobra Half-tracks"  },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body8MBT"          , propulsion: "tracked01", name: "Hyper Velocity Cannon Scorpion Tracks"    },
	{ turrets: ["Rocket-BB"       ], body: "Body2SUP"          , propulsion: "HalfTrack", name: "Bunker Buster Leopard Half-tracks"        },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body5REC"          , propulsion: "tracked01", name: "Assault Cannon Cobra Tracks"              },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"         , propulsion: "tracked01", name: "Assault Cannon Panther Tracks"            },
	{ turrets: ["Rocket-BB"       ], body: "Body8MBT"          , propulsion: "HalfTrack", name: "Bunker Buster Scorpion Half-tracks"       },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body12SUP"         , propulsion: "tracked01", name: "Heavy Cannon Mantis Tracks"               },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body11ABT"         , propulsion: "tracked01", name: "Heavy Cannon Python Tracks"               },
	{ turrets: ["Rocket-BB"       ], body: "Body6SUPP"         , propulsion: "HalfTrack", name: "Bunker Buster Panther Half-tracks"        },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body11ABT"         , propulsion: "tracked01", name: "Twin Assault Cannon Python Tracks"        },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"          , propulsion: "tracked01", name: "Twin Assault Cannon Tiger Tracks"         },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body4ABT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Bug VTOL"              },
	{ turrets: ["RailGun1Mk1"     ], body: "Body12SUP"         , propulsion: "tracked01", name: "Needle Gun Mantis Tracks"                 },
	{ turrets: ["RailGun1Mk1"     ], body: "Body12SUP"         , propulsion: "tracked01", name: "Needle Gun Mantis Tracks"                 },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body1REC"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Viper VTOL"            },
	{ turrets: ["RailGun1Mk1"     ], body: "Body12SUP"         , propulsion: "tracked01", name: "Needle Gun Mantis Tracks"                 },
	{ turrets: ["RailGun1Mk1"     ], body: "Body11ABT"         , propulsion: "tracked01", name: "Needle Gun Python Tracks"                 },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body2SUP"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Leopard VTOL"          },
	{ turrets: ["RailGun1Mk1"     ], body: "Body11ABT"         , propulsion: "tracked01", name: "Needle Gun Python Tracks"                 },
	{ turrets: ["RailGun1Mk1"     ], body: "Body11ABT"         , propulsion: "tracked01", name: "Needle Gun Python Tracks"                 },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body8MBT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Scorpion VTOL"         },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01", name: "Needle Gun Tiger Tracks"                  },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01", name: "Needle Gun Tiger Tracks"                  },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body3MBT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Retaliation VTOL"      },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01", name: "Needle Gun Tiger Tracks"                  },
	{ turrets: ["RailGun1Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"            },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body5REC"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Cobra VTOL"            },
	{ turrets: ["RailGun1Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"            },
	{ turrets: ["RailGun1Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"            },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body6SUPP"         , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Panther VTOL"          },
	{ turrets: ["RailGun1Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"            },
	{ turrets: ["RailGun1Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"            },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Retribution VTOL"      },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun1-VTOL"   ], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Needle Gun Retribution VTOL"         },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun2-VTOL"   ], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Rail Gun Retribution VTOL"           },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["ParticleGun-VTOL"], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Particle Gun Retribution VTOL"       },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"                },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["ParticleGun-VTOL"], body: "Body10MBT"         , propulsion: "V-Tol"    , name: "VTOL Particle Gun Vengeance VTOL"         },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["ParticleGun-VTOL"], body: "Body13SUP"         , propulsion: "V-Tol"    , name: "VTOL Particle Gun Wyvern VTOL"            },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"               },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks"  },
];
