const TEMPLATES = [
	{ turrets: ["BaBaMG"        ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs"  , name: "Machinegun Person"                                 },
	{ turrets: ["bTrikeMG"      ], body: "B4body-sml-trike01", propulsion: "BaBaProp"  , name: "Machinegun Trike"                                  },
	{ turrets: ["BJeepMG"       ], body: "B2JeepBody"        , propulsion: "BaBaProp"  , name: "Machinegun Jeep"                                   },
	{ turrets: ["BabaRocket"    ], body: "B2RKJeepBody"      , propulsion: "BaBaProp"  , name: "Scavenger Rocket Jeep"                             },
	{ turrets: ["BuggyMG"       ], body: "B3body-sml-buggy01", propulsion: "BaBaProp"  , name: "Machinegun Buggy"                                  },
	{ turrets: ["BabaRocket"    ], body: "B3bodyRKbuggy01"   , propulsion: "BaBaProp"  , name: "Scavenger Rocket Buggy"                            },
	{ turrets: ["BabaFlame"     ], body: "FireBody"          , propulsion: "BaBaProp"  , name: "Scavenger Flamer Firetruck"                        },
	{ turrets: ["BusCannon"     ], body: "FireBody"          , propulsion: "BaBaProp"  , name: "Scavenger Cannon Firetruck"                        },
	{ turrets: ["BabaFlame"     ], body: "BusBody"           , propulsion: "BaBaProp"  , name: "Scavenger Flamer Bus"                              },
	{ turrets: ["BusCannon"     ], body: "BusBody"           , propulsion: "BaBaProp"  , name: "Scavenger Cannon Bus"                              },
	{ turrets: ["MG1Mk1"        ], body: "Body1REC"          , propulsion: "wheeled01" , name: "Machinegun Viper Wheels"                           },
	{ turrets: ["MG2Mk1"        ], body: "Body1REC"          , propulsion: "HalfTrack" , name: "Twin Machinegun Viper Half-tracks"                 },
	{ turrets: ["Cannon1Mk1"    ], body: "Body1REC"          , propulsion: "HalfTrack" , name: "Light Cannon Viper Half-tracks"                    },
	{ turrets: ["CyborgChaingun"], body: "CyborgLightBody"   , propulsion: "CyborgLegs", name: "Machinegunner Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Cannon1Mk1"    ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Light Cannon Cobra Half-tracks"                    },
	{ turrets: ["MG3Mk1"        ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Heavy Machinegun Cobra Half-tracks"                },
	{ turrets: ["Rocket-Pod"    ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Mini-Rocket Pod Cobra Half-tracks"                 },
	{ turrets: ["Cannon2A-TMk1" ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Medium Cannon Cobra Half-tracks"                   },
	{ turrets: ["Rocket-MRL"    ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Mini-Rocket Array Cobra Half-tracks"               },
	{ turrets: ["Cannon2A-TMk1" ], body: "Body8MBT"          , propulsion: "tracked01" , name: "Medium Cannon Scorpion Tracks"                     },
	{ turrets: ["Rocket-LtA-T"  ], body: "Body5REC"          , propulsion: "HalfTrack" , name: "Lancer Cobra Half-tracks"                          },
	{ turrets: ["Rocket-LtA-T"  ], body: "Body11ABT"         , propulsion: "HalfTrack" , name: "Lancer Python Half-tracks"                         },
	{ turrets: ["Cannon4AUTOMk1"], body: "Body11ABT"         , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Python Half-tracks"          },
	{ turrets: ["Cannon4AUTOMk1"], body: "Body12SUP"         , propulsion: "tracked01" , name: "Hyper Velocity Cannon Mantis Tracks"               },
];
