const TEMPLATES = [
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["BaBaMG"          ], body: "B1BaBaPerson01"    , propulsion: "BaBaLegs" , name: "*BaBa MG* *BaBa Body* BaBaLegs"          },
	{ turrets: ["bTrikeMG"        ], body: "B4body-sml-trike01", propulsion: "BaBaProp" , name: "*Trike MG* *Trike Body* BaBaProp"        },
	{ turrets: ["x2_BuggyMG"         ], body: "x2_B3body-sml-buggy01", propulsion: "x2_BaBaProp" , name: "Big *Buggy MG* *Buggy Body* BaBaProp"        },
	{ turrets: ["BJeepMG"         ], body: "B2JeepBody"        , propulsion: "BaBaProp" , name: "*Jeep MG* *Jeep Body* BaBaProp"          },
	{ turrets: ["x3_BusCannon"       ], body: "x3_BusBody"           , propulsion: "x3_BaBaProp" , name: "Super Big *BusCannon* *School Bus Body* BaBaProp"  },
	{ turrets: ["Cannon1Mk1"      ], body: "Body1REC"          , propulsion: "wheeled01", name: "Light Cannon Viper Wheels"               },
	{ turrets: ["x2_Cannon1Mk1"      ], body: "x2_Body1REC"          , propulsion: "x2_HalfTrack", name: "Big Light Cannon Viper Half-tracks"          },
	{ turrets: ["Cannon1Mk1"      ], body: "Body8MBT"          , propulsion: "HalfTrack", name: "Light Cannon Scorpion Half-tracks"       },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body5REC"          , propulsion: "wheeled01", name: "Medium Cannon Cobra Wheels"              },
	{ turrets: ["x2_Cannon2A-TMk1"   ], body: "x2_Body5REC"          , propulsion: "x2_HalfTrack", name: "Big Medium Cannon Cobra Half-tracks"         },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body5REC"          , propulsion: "HalfTrack", name: "Hyper Velocity Cannon Cobra Half-tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body8MBT"          , propulsion: "tracked01", name: "Hyper Velocity Cannon Scorpion Tracks"   },
	{ turrets: ["Rocket-BB"       ], body: "Body2SUP"          , propulsion: "HalfTrack", name: "Bunker Buster Leopard Half-tracks"       },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body5REC"          , propulsion: "tracked01", name: "Assault Cannon Cobra Tracks"             },
	{ turrets: ["x3_Cannon5VulcanMk1"], body: "x3_Body6SUPP"         , propulsion: "x3_tracked01", name: "Super Big Assault Cannon Panther Tracks"           },
	{ turrets: ["Rocket-BB"       ], body: "Body8MBT"          , propulsion: "HalfTrack", name: "Bunker Buster Scorpion Half-tracks"      },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body12SUP"         , propulsion: "tracked01", name: "Heavy Cannon Mantis Tracks"              },
	{ turrets: ["x2_Cannon375mmMk1"  ], body: "x2_Body11ABT"         , propulsion: "x2_tracked01", name: "Big Heavy Cannon Python Tracks"              },
	{ turrets: ["Rocket-BB"       ], body: "Body6SUPP"         , propulsion: "HalfTrack", name: "Bunker Buster Panther Half-tracks"       },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body11ABT"         , propulsion: "tracked01", name: "Twin Assault Cannon Python Tracks"       },
	{ turrets: ["x2_Cannon6TwinAslt" ], body: "x2_Body9REC"          , propulsion: "x2_tracked01", name: "Big Twin Assault Cannon Tiger Tracks"        },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body4ABT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Bug VTOL"             },
	{ turrets: ["RailGun1Mk1"     ], body: "Body12SUP"         , propulsion: "tracked01", name: "Needle Gun Mantis Tracks"                },
	{ turrets: ["x4_RailGun1Mk1"     ], body: "x4_Body12SUP"         , propulsion: "x4_tracked01", name: "Massive Needle Gun Mantis Tracks"                },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body1REC"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Viper VTOL"           },
	{ turrets: ["RailGun1Mk1"     ], body: "Body12SUP"         , propulsion: "tracked01", name: "Needle Gun Mantis Tracks"                },
	{ turrets: ["x2_RailGun1Mk1"     ], body: "x2_Body11ABT"         , propulsion: "x2_tracked01", name: "Big Needle Gun Python Tracks"                },
	{ turrets: ["x2_Rocket-VTOL-BB"  ], body: "x2_Body2SUP"          , propulsion: "x2_V-Tol"    , name: "Big VTOL Bunker Buster Leopard VTOL"         },
	{ turrets: ["RailGun1Mk1"     ], body: "Body11ABT"         , propulsion: "tracked01", name: "Needle Gun Python Tracks"                },
	{ turrets: ["x3_RailGun1Mk1"     ], body: "x3_Body11ABT"         , propulsion: "x3_tracked01", name: "Super Big Needle Gun Python Tracks"                },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body8MBT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Scorpion VTOL"        },
	{ turrets: ["RailGun1Mk1"     ], body: "Body9REC"          , propulsion: "tracked01", name: "Needle Gun Tiger Tracks"                 },
	{ turrets: ["x2_RailGun1Mk1"     ], body: "x2_Body9REC"          , propulsion: "x2_tracked01", name: "Big Needle Gun Tiger Tracks"                 },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body3MBT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Retaliation VTOL"     },
	{ turrets: ["x3_RailGun1Mk1"     ], body: "x3_Body9REC"          , propulsion: "x3_tracked01", name: "Super Big Needle Gun Tiger Tracks"                 },
	{ turrets: ["x3_RailGun1Mk1"     ], body: "x3_Body7ABT"          , propulsion: "x3_tracked01", name: "Super Big Needle Gun Retribution Tracks"           },
	{ turrets: ["x2_Rocket-VTOL-BB"  ], body: "x2_Body5REC"          , propulsion: "x2_V-Tol"    , name: "Big VTOL Bunker Buster Cobra VTOL"           },
	{ turrets: ["RailGun1Mk1"     ], body: "Body7ABT"          , propulsion: "tracked01", name: "Needle Gun Retribution Tracks"           },
	{ turrets: ["x3_RailGun2Mk1"     ], body: "x3_Body10MBT"         , propulsion: "x3_tracked01", name: "Super Big Rail Gun Vengeance Tracks"               },
	{ turrets: ["x2_Rocket-VTOL-BB"  ], body: "x2_Body6SUPP"         , propulsion: "x2_V-Tol"    , name: "Big VTOL Bunker Buster Panther VTOL"         },
	{ turrets: ["x5_RailGun2Mk1"     ], body: "x5_Body10MBT"         , propulsion: "x5_tracked01", name: "Super Massive Rail Gun Vengeance Tracks"               },
	{ turrets: ["RailGun2Mk1"     ], body: "Body10MBT"         , propulsion: "tracked01", name: "Rail Gun Vengeance Tracks"               },
	{ turrets: ["Rocket-VTOL-BB"  ], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Bunker Buster Retribution VTOL"     },
	{ turrets: ["x3_RailGun2Mk1"     ], body: "x3_Body10MBT"         , propulsion: "x3_tracked01", name: "Super Big Rail Gun Vengeance Tracks"               },
	{ turrets: ["x2_RailGun2Mk1"     ], body: "x2_Body10MBT"         , propulsion: "x2_tracked01", name: "Big Rail Gun Vengeance Tracks"               },
	{ turrets: ["RailGun1-VTOL"   ], body: "Body7ABT"          , propulsion: "V-Tol"    , name: "VTOL Needle Gun Retribution VTOL"        },
	{ turrets: ["x2_RailGun2Mk1"     ], body: "x2_Body10MBT"         , propulsion: "x2_tracked01", name: "Big Rail Gun Vengeance Tracks"               },
	{ turrets: ["x3_RailGun2Mk1"     ], body: "x3_Body10MBT"         , propulsion: "x3_tracked01", name: "Super Big Rail Gun Vengeance Tracks"               },
	{ turrets: ["x2_RailGun2-VTOL"   ], body: "x2_Body7ABT"          , propulsion: "x2_V-Tol"    , name: "Big VTOL Rail Gun Retribution VTOL"          },
	{ turrets: ["RailGun3Mk1"     ], body: "Body13SUP"         , propulsion: "tracked01", name: "Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x4_RailGun3Mk1"     ], body: "x4_Body13SUP"         , propulsion: "x4_tracked01", name: "Massive Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x2_ParticleGun-VTOL"], body: "x2_Body7ABT"          , propulsion: "x2_V-Tol"    , name: "Big VTOL Particle Gun Retribution VTOL"      },
	{ turrets: ["x2_RailGun3Mk1"     ], body: "x2_Body13SUP"         , propulsion: "x2_tracked01", name: "Big Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x4_RailGun3Mk1"     ], body: "x4_Body13SUP"         , propulsion: "x4_tracked01", name: "Massive Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x3_ParticleGun-VTOL"], body: "x3_Body10MBT"         , propulsion: "x3_V-Tol"    , name: "Super Big VTOL Particle Gun Vengeance VTOL"        },
	{ turrets: ["x2_RailGun3Mk1"     ], body: "x2_Body13SUP"         , propulsion: "x2_tracked01", name: "Big Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x4_RailGun3Mk1"     ], body: "x4_Body13SUP"         , propulsion: "x4_tracked01", name: "Massive Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x3_ParticleGun-VTOL"], body: "x3_Body13SUP"         , propulsion: "x3_V-Tol"    , name: "Super Big VTOL Particle Gun Wyvern VTOL"           },
	{ turrets: ["x2_RailGun3Mk1"     ], body: "x2_Body13SUP"         , propulsion: "x2_tracked01", name: "Big Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x4_RailGun3Mk1"     ], body: "x4_Body13SUP"         , propulsion: "x4_tracked01", name: "Massive Gauss Cannon Wyvern Tracks"              },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "tracked01", name: "Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["RailGun3Mk1","RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01"  , name: "Gauss Cannon Gauss Cannon Dragon Hover"  },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
	{ turrets: ["x5_RailGun3Mk1","x5_RailGun3Mk1"], body: "x5_Body14SUP", propulsion: "x5_tracked01", name: "Super Massive Gauss Cannon Gauss Cannon Dragon Tracks" },
];
