const TEMPLATES = [
	null,
	null,
	null,
	null,
	null,
	{ turrets: ["MG1Mk1"                      ], body: "Body4ABT" , propulsion: "hover01", name: "Machinegun Bug Hover"                           },
	{ turrets: ["MG1Mk1"                      ], body: "Body4ABT" , propulsion: "hover01", name: "Machinegun Bug Hover"                           },
	{ turrets: ["MG1Mk1"                      ], body: "Body4ABT" , propulsion: "hover01", name: "Machinegun Bug Hover"                           },
	{ turrets: ["MG1Mk1"                      ], body: "Body4ABT" , propulsion: "hover01", name: "Machinegun Bug Hover"                           },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body4ABT" , propulsion: "hover01", name: "Light Cannon Bug Hover"                         },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body4ABT" , propulsion: "hover01", name: "Light Cannon Bug Hover"                         },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body1REC" , propulsion: "hover01", name: "Light Cannon Viper Hover"                       },
	{ turrets: ["Cannon1Mk1"                  ], body: "Body1REC" , propulsion: "hover01", name: "Light Cannon Viper Hover"                       },
	{ turrets: ["Cannon2A-TMk1"               ], body: "Body8MBT" , propulsion: "hover01", name: "Medium Cannon Scorpion Hover"                   },
	{ turrets: ["Cannon2A-TMk1"               ], body: "Body5REC" , propulsion: "hover01", name: "Medium Cannon Cobra Hover"                      },
	{ turrets: ["Cannon4AUTOMk1"              ], body: "Body8MBT" , propulsion: "hover01", name: "Hyper Velocity Cannon Scorpion Hover"           },
	{ turrets: ["Cannon4AUTOMk1"              ], body: "Body5REC" , propulsion: "hover01", name: "Hyper Velocity Cannon Cobra Hover"              },
	{ turrets: ["Rocket-BB"                   ], body: "Body2SUP" , propulsion: "hover01", name: "Bunker Buster Leopard Hover"                    },
	{ turrets: ["Cannon5VulcanMk1"            ], body: "Body8MBT" , propulsion: "hover01", name: "Assault Cannon Scorpion Hover"                  },
	{ turrets: ["Cannon5VulcanMk1"            ], body: "Body5REC" , propulsion: "hover01", name: "Assault Cannon Cobra Hover"                     },
	{ turrets: ["Rocket-BB"                   ], body: "Body5REC" , propulsion: "hover01", name: "Bunker Buster Cobra Hover"                      },
	{ turrets: ["Cannon375mmMk1"              ], body: "Body12SUP", propulsion: "hover01", name: "Heavy Cannon Mantis Hover"                      },
	{ turrets: ["Cannon375mmMk1"              ], body: "Body11ABT", propulsion: "hover01", name: "Heavy Cannon Python Hover"                      },
	{ turrets: ["Rocket-BB"                   ], body: "Body12SUP", propulsion: "hover01", name: "Bunker Buster Mantis Hover"                     },
	{ turrets: ["Cannon6TwinAslt"             ], body: "Body12SUP", propulsion: "hover01", name: "Twin Assault Cannon Mantis Hover"               },
	{ turrets: ["Cannon6TwinAslt"             ], body: "Body11ABT", propulsion: "hover01", name: "Twin Assault Cannon Python Hover"               },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body9REC" , propulsion: "hover01", name: "Needle Gun Tiger Hover"                         },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT" , propulsion: "hover01", name: "Needle Gun Retribution Hover"                   },
	{ turrets: ["Rocket-VTOL-BB"              ], body: "Body6SUPP", propulsion: "V-Tol"  , name: "VTOL Bunker Buster Panther VTOL"                },
	{ turrets: ["RailGun1Mk1"                 ], body: "Body7ABT" , propulsion: "hover01", name: "Needle Gun Retribution Hover"                   },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT" , propulsion: "V-Tol"  , name: "VTOL Rail Gun Retribution VTOL"                 },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT" , propulsion: "V-Tol"  , name: "VTOL Rail Gun Retribution VTOL"                 },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT" , propulsion: "V-Tol"  , name: "VTOL Rail Gun Retribution VTOL"                 },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2Mk1"                 ], body: "Body10MBT", propulsion: "hover01", name: "Rail Gun Vengeance Hover"                       },
	{ turrets: ["RailGun2-VTOL"               ], body: "Body7ABT" , propulsion: "V-Tol"  , name: "VTOL Rail Gun Retribution VTOL"                 },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body7ABT" , propulsion: "V-Tol"  , name: "VTOL Particle Gun Retribution VTOL"             },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body10MBT", propulsion: "V-Tol"  , name: "VTOL Particle Gun Vengeance VTOL"               },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["ParticleGun-VTOL"            ], body: "Body13SUP", propulsion: "V-Tol"  , name: "VTOL Particle Gun Wyvern VTOL"                  },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["RailGun3Mk1"                 ], body: "Body13SUP", propulsion: "hover01", name: "Gauss Cannon Wyvern Hover"                      },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
	{ turrets: ["Missile-MdArt", "RailGun3Mk1"], body: "Body14SUP", propulsion: "hover01", name: "Gauss Cannon Seraph Missile Array Dragon Hover" },
];
