const TEMPLATES = [
	{ turrets: ["MG2Mk1"          ], body: "Body2SUP"       , propulsion: "wheeled01" , name: "Twin Machinegun Leopard Wheels" },
	{ turrets: ["Cannon1Mk1"      ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Light Cannon Leopard Half-tracks" },
	{ turrets: ["CyborgChaingun"  ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "Machinegunner Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Flame1Mk1"       ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Flamer Leopard Half-tracks" },
	{ turrets: ["MG3Mk1"          ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Heavy Machinegun Leopard Half-tracks" },
	{ turrets: ["CyborgFlamer01"  ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "Cyborg Flamer Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Rocket-Pod"      ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Mini-Rocket Pod Leopard Half-tracks" },
	{ turrets: ["Mortar1Mk1"      ], body: "Body2SUP"       , propulsion: "wheeled01" , name: "Mortar Leopard Wheels" },
	{ turrets: ["CyborgCannon"    ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "Heavy Gunner Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Cannon2A-TMk1"   ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Medium Cannon Panther Half-tracks" },
	{ turrets: ["Rocket-MRL"      ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Mini-Rocket Array Leopard Half-tracks" },
	{ turrets: ["Cyb-Wpn-Grenade" ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "*Cyborg Grenade Weapon* Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Cannon1Mk1"      ], body: "Body2SUP"       , propulsion: "tracked01" , name: "Light Cannon Leopard Tracks" },
	{ turrets: ["MG3Mk1"          ], body: "Body2SUP"       , propulsion: "tracked01" , name: "Heavy Machinegun Leopard Tracks" },
	{ turrets: ["Rocket-LtA-T"    ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Lancer Leopard Half-tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Leopard Half-tracks" },
	{ turrets: ["CyborgRocket"    ], body: "CyborgLightBody", propulsion: "CyborgLegs", name: "Cyborg Lancer Cyborg Light Body Cyborg Propulsion" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Hyper Velocity Cannon Panther Half-tracks" },
	{ turrets: ["Mortar3ROTARYMk1"], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Pepperpot Panther Tracks" },
	{ turrets: ["Rocket-BB"       ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Bunker Buster Leopard Half-tracks" },
	{ turrets: ["QuadMg1AAGun"    ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Hurricane AA Turret Panther Half-tracks" },
	{ turrets: ["MG4ROTARYMk1"    ], body: "Body2SUP"       , propulsion: "HalfTrack" , name: "Assault Gun Leopard Half-tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Hyper Velocity Cannon Panther Tracks" },
	{ turrets: ["MG4ROTARYMk1"    ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Assault Gun Panther Half-tracks" },
	{ turrets: ["Flame2"          ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Inferno Panther Tracks" },
	{ turrets: ["Cyb-Hvywpn-Mcannon"], body: "CyborgHeavyBody", propulsion: "CyborgLegs", name: "Super Heavy-Gunner Cyborg Heavy Body Cyborg Propulsion" },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Assault Cannon Panther Half-tracks" },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Assault Cannon Panther Tracks" },
	{ turrets: ["Rocket-MRL-Hvy"  ], body: "Body2SUP"       , propulsion: "tracked01" , name: "Heavy Rocket Array Leopard Tracks" },
	{ turrets: ["Rocket-MRL-Hvy"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Heavy Rocket Array Panther Tracks" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body6SUPP"      , propulsion: "HalfTrack" , name: "Heavy Cannon Panther Half-tracks" },
	{ turrets: ["MG4ROTARYMk1"    ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Assault Gun Panther Tracks" },
	{ turrets: ["Bomb1-VTOL-LtHE" ], body: "Body2SUP"       , propulsion: "V-Tol"     , name: "VTOL Cluster Bomb Bay Leopard VTOL" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Heavy Cannon Panther Tracks" },
	{ turrets: ["Cannon4AUTOMk1"  ], body: "Body9REC"       , propulsion: "tracked01" , name: "Hyper Velocity Cannon Tiger Tracks" },
	{ turrets: ["MG4ROTARYMk1"    ], body: "Body9REC"       , propulsion: "tracked01" , name: "Assault Gun Tiger Tracks" },
	{ turrets: ["Cannon5VulcanMk1"], body: "Body9REC"       , propulsion: "tracked01" , name: "Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon375mmMk1"  ], body: "Body9REC"       , propulsion: "tracked01" , name: "Heavy Cannon Tiger Tracks" },
	{ turrets: ["Rocket-HvyA-T"   ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Tank Killer Panther Tracks" },
	{ turrets: ["Rocket-HvyA-T"   ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Tank Killer Panther Tracks" },
	{ turrets: ["Rocket-HvyA-T"   ], body: "Body6SUPP"      , propulsion: "tracked01" , name: "Tank Killer Panther Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" },
	{ turrets: ["Cannon6TwinAslt" ], body: "Body9REC"       , propulsion: "tracked01" , name: "Twin Assault Cannon Tiger Tracks" }
];
